version: '3.8'

services:
  stylometry:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: python pipeline.py
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
  umap: 
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ./data:/app/data
    command: python umap_server.py